# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmstring',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConfirmString',
        ),
    ]
